import { AI_SDK_PACKAGES } from "../src/detect/ai-sdk.js";
import { defaultRegistry } from "../src/detect/registry/index.js";
import type { IrLanguage } from "../src/lang/ir/language.js";
import { phpLanguage } from "../src/lang/php/index.js";
import { pythonLanguage } from "../src/lang/python/index.js";
import { PROVIDERS } from "../src/normalize/provider.js";
import type { Ecosystem } from "../src/report/schema.js";

interface Column {
  title: string;
  ecosystem: Ecosystem;
  /** Methods the registry lists for a package, 0 when there is no registry. */
  methods(pkg: string): number;
  clients: string[];
}

function typescriptColumn(): Column {
  const registry = defaultRegistry();
  return {
    title: "TypeScript (npm)",
    ecosystem: "npm",
    methods: (pkg) => {
      const e = registry.byPackage(pkg);
      if (e) return Object.keys(e.methods ?? {}).length + Object.keys(e.commands ?? {}).length;
      return AI_SDK_PACKAGES.has(pkg) ? 1 : 0;
    },
    clients: ["fetch", "axios", "got", "ky", "node http/https", "AI SDK", "n8n / activepieces helpers"],
  };
}

function irColumn(title: string, lang: IrLanguage): Column {
  return {
    title,
    ecosystem: lang.ecosystem,
    methods: (pkg) =>
      lang.registry.filter((r) => lang.normalizePackage(r.package) === lang.normalizePackage(pkg) || r.aliases?.includes(pkg)).reduce((n, r) => n + Object.keys(r.methods).length, 0),
    clients: [...new Set([...lang.clients.map((c) => c.client), ...(lang.id === "python" ? ["urllib"] : ["curl", "php-stream"])])],
  };
}

export const COLUMNS: Column[] = [typescriptColumn(), irColumn("Python (PyPI)", pythonLanguage), irColumn("PHP (Composer)", phpLanguage)];

function cell(col: Column, packages: string[] | undefined): string {
  if (!packages || packages.length === 0) return "";
  return packages.map((p) => (col.methods(p) > 0 ? `**\`${p}\`**` : `\`${p}\``)).join(", ");
}

/** The SDK support matrix: every provider with a known SDK, and per language which packages have a registry. */
export function supportMarkdown(): string {
  const rows = PROVIDERS.filter((p) => COLUMNS.some((c) => (p.packages?.[c.ecosystem] ?? []).length > 0)).map((p) => {
    const cells = COLUMNS.map((c) => cell(c, p.packages?.[c.ecosystem]));
    return `| ${p.name} | ${cells.join(" | ")} |`;
  });
  const supported = COLUMNS.map((c) => {
    const pkgs = PROVIDERS.flatMap((p) => p.packages?.[c.ecosystem] ?? []).filter((p) => c.methods(p) > 0);
    return `| ${c.title} | ${new Set(pkgs).size} | ${c.clients.map((x) => `\`${x}\``).join(", ")} |`;
  });
  return [
    "# SDK support by language",
    "",
    "Generated by `pnpm gen:support` from the SDK registries and [`src/normalize/providers.json`](../src/normalize/providers.json); do not edit by hand.",
    "",
    "A **bold** package has a registry: its calls are listed with their method, path and body. A plain package is known",
    "but has no registry yet: a scan reports it in `coverage.sdks` as `unsupported` when the code imports it, so its calls",
    "are never silently missing. Raw HTTP calls to a provider's host are found in every language, with or without an SDK.",
    "",
    "| language | packages with a registry | HTTP clients |",
    "|---|---|---|",
    ...supported,
    "",
    `| provider | ${COLUMNS.map((c) => c.title).join(" | ")} |`,
    `|---|${COLUMNS.map(() => "---").join("|")}|`,
    ...rows,
    "",
  ].join("\n");
}
